# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='status',
            field=models.CharField(blank=True, default=b'CREATED', max_length=1000, null=True),
        ),
    ]
